CREATE TABLE users (
    id bigint generated by DEFAULT AS identity PRIMARY key,
    email text,
    password text,
    username text,
    first_name text,
    last_name text,
    timestamp timestamp WITH time zone,
);