# Generated by Django 4.1.6 on 2023-02-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=240, verbose_name='timestamp')),
                ('company', models.CharField(max_length=240, verbose_name='timestamp')),
                ('level', models.CharField(max_length=240, verbose_name='timestamp')),
                ('title', models.CharField(max_length=240, verbose_name='timestamp')),
                ('totalyearlycompensation', models.CharField(max_length=240, verbose_name='timestamp')),
                ('location', models.CharField(max_length=240, verbose_name='timestamp')),
                ('yearsofexperience', models.CharField(max_length=240, verbose_name='timestamp')),
                ('yearsatcompany', models.CharField(max_length=240, verbose_name='timestamp')),
                ('tag', models.CharField(max_length=240, verbose_name='timestamp')),
                ('basesalary', models.CharField(max_length=240, verbose_name='timestamp')),
                ('stockgrantvalue', models.CharField(max_length=240, verbose_name='timestamp')),
                ('bonus', models.CharField(max_length=240, verbose_name='timestamp')),
                ('gender', models.CharField(max_length=240, verbose_name='timestamp')),
                ('otherdetails', models.CharField(max_length=240, verbose_name='timestamp')),
                ('cityid', models.CharField(max_length=240, verbose_name='timestamp')),
                ('dmaid', models.CharField(max_length=240, verbose_name='timestamp')),
                ('rowNumber', models.CharField(max_length=240, verbose_name='timestamp')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
