CREATE TABLE levels (
    id uuid default uuid_generate_v4() NOT NULL UNIQUE,
    company_id uuid NOT NULL,
    title TEXT,
    location TEXT,
    level TEXT,
    tag TEXT,
    notes TEXT ,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    years_of_experience SMALLINT,
    years_at_company SMALLINT,
    base_salary INT,
    stock_grant_value INT,
    bonus INT,
    yearly_compensation INT,
    gender gender DEFAULT "UNSPECIFIED",
    FOREIGN KEY (company_id) REFERENCES companies (id),
    PRIMARY KEY (id)
);