CREATE TABLE levels (
    id uuid default uuid_generate_v4(),
    company_id uuid not null,
    title text,
    location text,
    level text,
    tag text,
    notes text,
    created_at timestamp WITH time zone,
    updated_at timestamp WITH time zone,
    years_of_experience smallint,
    years_at_company smallint,
    base_salary int,
    stock_grant_value int,
    bonus int,
    yearly_compensation int,
    gender gender,
    FOREIGN KEY (company_id) REFERENCES public.companies (id),
    primary key (id)
);