CREATE TABLE levels (
    id bigint generated by DEFAULT AS identity PRIMARY key,
    company text,
    title text,
    location text,
    level text,
    tag text,
    notes text,
    created_at timestamp WITH time zone,
    updated_at timestamp WITH time zone,
    years_of_experience smallint,
    years_at_company smallint,
    base_salary int,
    stock_grant_value int,
    bonus int,
    yearly_compensation int,
    gender gender
);